### PR TITLE
Create database , create table and query data

### PR DESCRIPTION
**Pull request by leonard33**
CREATE DATABASE VET_CLINIC AND CREATE TABLE animals, QUERY DATA from the table

Create a database named vet_clinic.
Create a table named animals with the following columns:
id: integer
name: string
date_of_birth: date
escape_attempts: integer
neutered: boolean
weight_kg: decimal
Copy the SQL you used in the previous point into the schema.sql file in the generated repository.
Insert the following data:
Animal: His name is Agumon. He was born on Feb 3rd, 2020, and currently weighs 10.23kg. He was neutered and he has never tried to escape.
Animal: Her name is Gabumon. She was born on Nov 15th, 2018, and currently weighs 8kg. She is neutered and she has tried to escape 2 times.
Animal: His name is Pikachu. He was born on Jan 7th, 2021, and currently weighs 15.04kg. He was not neutered and he has tried to escape once.
Animal: Her name is Devimon. She was born on May 12th, 2017, and currently weighs 11kg. She is neutered and she has tried to escape 5 times.
Copy the SQL you used in the previous point into the data.sql file in the generated repository.
Write queries for the following quests:
Find all animals whose name ends in "mon".
List the name of all animals born between 2016 and 2019.
List the name of all animals that are neutered and have less than 3 escape attempts.
List the date of birth of all animals named either "Agumon" or "Pikachu".
List name and escape attempts of animals that weigh more than 10.5kg
Find all animals that are neutered.
Find all animals not named Gabumon.
Find all animals with a weight between 10.4kg and 17.3kg (including the animals with the weights that equals precisely 10.4kg or 17.3kg)

### CODE REVIEW

**Comment by leonard33** [comment]
Create database vet_clinic and table animals
Screenshot from 2022-07-05 11-50-58

**Comment by leonard33** [comment]
INSERT INTO animals (name, date_of_birth, weight_kg, neutered, escape_attempts) 
VALUES ('Agumon', 'Feb 3, 2020', 10.23, true, 0),
('Gabumon', 'Nov 15, 2018', 8, true, 2),
('Pikachu', 'Jan 7, 2021', 15.04, false, 1),
('Devimon', 'May 12, 2017', 11, true, 5);
Screenshot from 2022-07-05 12-02-34

**Comment by leonard33** [comment]
SELECT * FROM animals WHERE name LIKE '%mon';
SELECT name FROM animals WHERE date_of_birth >= '2016-01-01' AND date_of_birth <= '2019-12-31';
SELECT name FROM animals WHERE neutered = 'true' AND escape_attempts < 3;
Screenshot from 2022-07-05 12-19-43

**Comment by leonard33** [comment]
SELECT date_of_birth FROM animals WHERE name = 'Agumon' OR name = 'Pikachu';
SELECT name, escape_attempts FROM animals WHERE weight_kg > 10.5;
SELECT * FROM animals WHERE neutered = 'true';
SELECT * FROM animals WHERE name <> 'Gabumon';
Screenshot from 2022-07-05 12-28-50

**Comment by leonard33** [comment]
SELECT * FROM animals WHERE weight_kg >= 10.4 AND weight_kg <= 17.3;
Screenshot from 2022-07-05 12-32-05

**Review by t-yanick — APPROVED** [review]
Hi @leonard33, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
